// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.EventSeat", b =>
                {
                    b.Property<Guid>("EventSeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventSectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid?>("ReservedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("SeatId")
                        .HasColumnType("bigint");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("EventSeatId");

                    b.HasIndex("EventSectorId");

                    b.HasIndex("StatusId");

                    b.ToTable("EventSeat", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.EventSector", b =>
                {
                    b.Property<Guid>("EventSectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsControlled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ReservedCount")
                        .HasColumnType("int");

                    b.Property<Guid>("SectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoldCount")
                        .HasColumnType("int");

                    b.HasKey("EventSectorId");

                    b.ToTable("EventSector", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TicketId");

                    b.HasIndex("StatusId");

                    b.ToTable("Ticket", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TicketSeat", b =>
                {
                    b.Property<Guid>("TicketSeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventSeatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EventSeatId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TicketSeatId");

                    b.HasIndex("EventSeatId");

                    b.HasIndex("EventSeatId1");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketSeat", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TicketSector", b =>
                {
                    b.Property<Guid>("TicketSectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventSectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EventSectorId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TicketSectorId");

                    b.HasIndex("EventSectorId");

                    b.HasIndex("EventSectorId1");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketSectors");
                });

            modelBuilder.Entity("Domain.Entities.TicketStatus", b =>
                {
                    b.Property<int>("StatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.HasKey("StatusID");

                    b.ToTable("TicketStatus", (string)null);

                    b.HasData(
                        new
                        {
                            StatusID = 1,
                            Name = "Available"
                        },
                        new
                        {
                            StatusID = 2,
                            Name = "Reserved"
                        },
                        new
                        {
                            StatusID = 3,
                            Name = "Sold"
                        },
                        new
                        {
                            StatusID = 4,
                            Name = "Expired"
                        });
                });

            modelBuilder.Entity("Domain.Entities.EventSeat", b =>
                {
                    b.HasOne("Domain.Entities.EventSector", "EventSectorRef")
                        .WithMany("EventSeats")
                        .HasForeignKey("EventSectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TicketStatus", "StatusRef")
                        .WithMany("EventSeats")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EventSectorRef");

                    b.Navigation("StatusRef");
                });

            modelBuilder.Entity("Domain.Entities.Ticket", b =>
                {
                    b.HasOne("Domain.Entities.TicketStatus", "StatusRef")
                        .WithMany("Tickets")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StatusRef");
                });

            modelBuilder.Entity("Domain.Entities.TicketSeat", b =>
                {
                    b.HasOne("Domain.Entities.EventSeat", "EventSeatRef")
                        .WithMany()
                        .HasForeignKey("EventSeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.EventSeat", null)
                        .WithMany("TicketSeats")
                        .HasForeignKey("EventSeatId1");

                    b.HasOne("Domain.Entities.Ticket", "TicketRef")
                        .WithMany("TicketSeats")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventSeatRef");

                    b.Navigation("TicketRef");
                });

            modelBuilder.Entity("Domain.Entities.TicketSector", b =>
                {
                    b.HasOne("Domain.Entities.EventSector", "EventSectorRef")
                        .WithMany()
                        .HasForeignKey("EventSectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.EventSector", null)
                        .WithMany("TicketSectors")
                        .HasForeignKey("EventSectorId1");

                    b.HasOne("Domain.Entities.Ticket", "TicketRef")
                        .WithMany("TicketSectors")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventSectorRef");

                    b.Navigation("TicketRef");
                });

            modelBuilder.Entity("Domain.Entities.EventSeat", b =>
                {
                    b.Navigation("TicketSeats");
                });

            modelBuilder.Entity("Domain.Entities.EventSector", b =>
                {
                    b.Navigation("EventSeats");

                    b.Navigation("TicketSectors");
                });

            modelBuilder.Entity("Domain.Entities.Ticket", b =>
                {
                    b.Navigation("TicketSeats");

                    b.Navigation("TicketSectors");
                });

            modelBuilder.Entity("Domain.Entities.TicketStatus", b =>
                {
                    b.Navigation("EventSeats");

                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
